const roomData = [
  {
    id: 1,
    name: "Oceanfront Paradise Swim-Up Studio",
    img: [
      "assets/images/room/oceanfront-paradise-swim-up-studio-room.webp",
      "assets/images/room/presidential-oceanfront-paradise-swim-up-studio-rooms-margaritaville-riviera-maya-2.webp",
      "assets/images/room/presidential-oceanfront-paradise-swim-up-studio-rooms-margaritaville-riviera-maya-3.webp",
      "assets/images/room/presidential-oceanfront-paradise-swim-up-studio-rooms-margaritaville-riviera-maya-4.webp",
    ],
    desc: "Estas suites cuentan con impresionantes vistas al mar Caribe y se dividen en dos partes: una zona de dormitorio de tamaño king y una zona de estar con sofá, mesa de comedor y 2 Smart TV, una amplia terraza que conduce a una piscina infinita. El cuarto de baño acristalado cuenta con bañera exenta y ducha de efecto lluvia.",
    person: 2,
    roomSize: "614 ft² | 57 m²",
    prices: {
      high: 10005,
      low: 9017,
      Diciembre: 13936,
      range: {
        low: "2025-04-13",
        high: "2025-04-19",
      },
    },
  },
  {
    id: 2,
    name: "Luxury Paradise Swim-Up Suite",
    img: [
      "assets/images/room/luxury-paradise-swim-up-suite-rooms-margaritaville-riviera-maya.webp",
    ],
    desc: "Estas suites ubicadas en la planta baja cuentan con cama tamaño King, área de estar con sofá y mesa lateral. El baño con loseta de vidrio cuenta con tina independiente y ducha con efecto de lluvia. La terraza tiene acceso a la piscina principal del hotel y está equipada con mesa, dos sillas y dos camastros ubicados en la parte poco profunda de la piscina.",
    person: 2,
    roomSize: "463 ft² | 43 m²",
    prices: {
      high: 8446,
      low: 7367,
      Diciembre: 12596,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 3,
    name: "King Paradise Swim-Up Suite",
    img: [
      "assets/images/room/king-paradise-swim-up-suite-room.webp",
      "assets/images/room/king-paradise-swim-up-suite-rooms-margaritaville-riviera-maya-5.webp",
      "assets/images/room/king-paradise-swim-up-suite-rooms-margaritaville-riviera-maya-3.webp",
      "assets/images/room/king-paradise-swim-up-suite-rooms-margaritaville-riviera-maya-1.webp",
      "assets/images/room/king-paradise-swim-up-suite-rooms-margaritaville-riviera-maya-4.webp",
    ],
    desc: "Estas cómodas y bien equipadas suites están ubicadas en la planta baja y ofrecen cama tamaño King, área de estar con sofá y mesa lateral. La terraza tiene acceso a la piscina principal y cuenta con mesa, dos sillas y dos camastros ubicados en la parte poco profunda de la piscina.",
    person: 2,
    roomSize: "452 ft² | 42 m²",
    prices: {
      high: 8671,
      low: 7690,
      Diciembre: 10985,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 4,
    name: "Coral Reefer Signature Suite",
    img: [
      "assets/images/room/two-bedroom-coral-reefer-signature-suite-room.webp",
      "assets/images/room/coral-reefer-signature-suite-rooms-margaritaville-riviera-maya-1.webp",
    ],
    desc: "Situadas en el centro de la 5ª (última) planta de la propiedad, las espectaculares suites Coral Reefer ofrecen el máximo lujo en un entorno realmente impresionante con unas vistas preciosas al mar. Al entrar en la impresionante sala de estar, los huéspedes descubrirán 3.200 pies cuadrados de impresionantes zonas de estar y comedor interiores y exteriores con un concepto abierto de sala de estar y comedor con capacidad para 8 personas y una zona de bar.",
    person: 4,
    roomSize: "1780 ft² | 165 m²",
    prices: {
      high: 14348,
      low: 13557,
      Diciembre: 14348,
      Enero: 14122,
      Febrero: 13859,
      Marzo: 13557,
      Abril: 13557,
      Mayo: 13521,
      Junio: 13561,
      Julio: 13644,
      Agosto: 13896,
      Septiembre: 13947,
      Octubre: 13901,
      Noviembre: 13810,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 5,
    name: "One Particular Harbour Suite",
    img: [
      "assets/images/room/one-particular-harbour-suite-rooms-margaritaville-riviera-maya-2.webp",
      "assets/images/room/one-particular-harbour-suite-rooms-margaritaville-riviera-maya-1.webp",
    ],
    desc: "Esta suite exclusiva frente al mar cuenta con king-size, zona de estar totalmente amueblada y sofá de diseño, Smart TV e impresionantes vistas desde la habitación y el balcón. El cuarto de baño, que se abre a la sala de estar, tiene lavabos para él y para ella, una bañera independiente y dos duchas efecto lluvia, así como un vestidor.",
    person: 2,
    roomSize: "678 ft² | 63 m²",
    prices: {
      high: 18978,
      low: 16889,
      Diciembre: 18978,
      Enero: 19059,
      Febrero: 18522,
      Marzo: 16981,
      Abril: 16889,
      Mayo: 16889,
      Junio: 16580,
      Julio: 16580,
      Agosto: 16783,
      Septiembre: 16783,
      Octubre: 16701,
      Noviembre: 17340,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 6,
    name: "Luxury Paradise Suite",
    img: ["assets/images/room/luxury-paradise-suite-room.webp"],
    desc: "Estas suites ofrecen cama tamaño King, área de estar con sofá y mesa lateral. El baño cuenta con loseta de vidrio, tina independiente y ducha con efecto de lluvia. La terraza cuenta con una mesa y dos sillas. Disponibles suites que conectan. Estas suites están ubicadas en el segundo, tercer y cuarto piso del hotel.",
    person: 2,
    roomSize: "463 ft² | 43 m²",
    prices: {
      high: 6428,
      low: 5843,
      Diciembre: 6428,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 7,
    name: "King Paradise Room",
    img: [
      "assets/images/room/king-paradise-room.webp",
      "assets/images/room/king-paradise-room-rooms-margaritaville-riviera-maya-3.webp",
      "assets/images/room/king-paradise-room-rooms-margaritaville-riviera-maya-2.webp",
      "assets/images/room/king-paradise-room-rooms-margaritaville-riviera-maya-5.webp",
    ],
    desc: "Estas cómodas y bien equipadas suites ofrecen cama tamaño King, área de estar con sofá y mesa lateral. La terraza cuenta con mesa y dos sillas.",
    person: 2,
    roomSize: "452 ft² | 42 m²",
    prices: {
      Diciembre: 6118,
      high: 6118,
      low: 5550,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 8,
    name: "Queen Paradise Room",
    img: ["assets/images/room/queen-paradise-room-room.webp"],
    desc: "Estas suites están ubicadas en el segundo, tercer y cuarto piso del hotel y ofrecen dos camas tamaño Queen y una mesa para dos personas. La terraza cuenta con mesa y dos sillas. Disponibles suites que conectan.",
    person: 3,
    roomSize: "452 ft² | 42 m²",
    prices: {
      Diciembre: 6179,
      high: 6179,
      low: 5627,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 9,
    name: "Beachfront Honeymoon Suite",
    img: ["assets/images/room/beachfront-honeymoon-suite-room.webp"],
    desc: "Esta suite con vista al mar cuenta con una cama tamaño King, área de estar completamente equipada sofá de diseño, smart TV e impresionante vista del Mar Caribe desde esta área y del balcón. El baño, que abre hacia el área de estar, cuenta con lavamanos para él y ella, tina independiente y dos regaderas tipo lluvia, al igual que vestidor.",
    person: 2,
    roomSize: "678 ft² | 63 m²",
    prices: {
      high: 10155,
      low: 9370,
      Diciembre: 10155,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 10,
    name: "Oceanfront Infinity Pool Suite",
    img: [
      "assets/images/room/oceanfront-infinity-pool-suite-room.webp",
      "assets/images/room/oceanfront-infinity-pool-suite-rooms-margaritaville-riviera-maya-2.webp",
    ],
    desc: "Ubicadas en la parte central del cuarto piso, estas suites cuentan con fantásticas vistas del mar y de la propiedad. Estas cómodas y bien equipadas suites ofrecen una cama tamaño King, área de estar y escritorio. Los baños con loseta de vidrio cuentan con tina independiente y ducha con efecto de lluvia. Los huéspedes pueden tener acceso directo a la piscina infinity directo desde su terraza.",
    person: 2,
    roomSize: "463 ft² | 43m²",
    prices: {
      Diciembre: 9809,
      high: 9809,
      low: 8207,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 11,
    name: "Oceanfront Paradise Studio",
    img: [
      "assets/images/room/oceanfront-paradise-studio-room.webp",
      "assets/images/room/oceanfront-paradise-studio-rooms-margaritaville-riviera-maya-5.webp",
      "assets/images/room/oceanfront-paradise-studio-rooms-margaritaville-riviera-maya-4.webp",
      "assets/images/room/oceanfront-paradise-studio-rooms-margaritaville-riviera-maya-7.webp",
      "assets/images/room/oceanfront-paradise-studio-rooms-margaritaville-riviera-maya-2.webp",
    ],
    desc: "Estas suites cuentan con magníficas vistas a la playa. Las suites están divididas en dos partes: una zona de dormitorio con cama king-size y una zona de estar con sofá, mesa de comedor y Smart TV, una terraza amueblada con mesa, sillas y sofá cama. El cuarto de baño acristalado cuenta con bañera exenta y ducha de efecto lluvia.",
    person: 2,
    roomSize: "614 ft² | 57 m²",
    prices: {
      Diciembre: 9285,
      high: 9285,
      low: 8207,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 12,
    name: "Oceanfront Chillout Suite",
    img: [
      "assets/images/room/oceanfront-chillout-suite-room.webp",
      "assets/images/room/oceanfront-chillout-suite-rooms-margaritaville-riviera-maya-2.webp",
      "assets/images/room/oceanfront-chillout-suite-rooms-margaritaville-riviera-maya-1.webp",
    ],
    desc: "Ubicadas en la parte central del quinto piso, estas suites cuentan con espléndidas vistas del mar y de la propiedad. Estas cómodas y bien equipadas suites ofrecen una cama tamaño King, área de estar con sofá y mesa lateral. Los baños con loseta de vidrio cuentan con tina independiente y ducha con efecto de lluvia. Las suites cuentan con terraza privada que permite tener vistas panorámicas del Mar Caribe.",
    person: 2,
    roomSize: "474 ft² | 44 m²",
    prices: {
      high: 7511,
      low: 6969,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
  {
    id: 13,
    name: "Island Oasis Suite",
    img: ["assets/images/room/island-oasis-suite-rooms.jpg"],
    desc: "Ubicada en la planta baja con vista a los exuberantes jardines, estas suites cuidadosamente diseñadas ofrecen cama tamaño King, área de estar con sofá y mesa lateral. La terraza tiene acceso a un oasis de jardín sereno que cuenta con una hamaca, área de descanso y una pared verde para agregarle un toque zen.",
    person: 2,
    roomSize: "452 ft² | 42 m²",
    prices: {
      high: 6694,
      low: 6034,
      range: {
        low: "2025-06-20",
        high: "2025-08-20",
      },
    },
  },
];

export default roomData;
